apiVersion: v1
kind: Service
metadata:
  name: ai-lecture-api
  namespace: ai-lecture
  labels:
    app: ai-lecture-api
spec:
  type: NodePort
  selector:
    app: ai-lecture-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30092
      protocol: TCP
