apiVersion: v1
kind: Service
metadata:
  name: ai-lecture-web
  namespace: ai-lecture
  labels:
    app: ai-lecture-web
spec:
  type: NodePort
  selector:
    app: ai-lecture-web
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30093
      protocol: TCP
